### ISSUE TITLE
For more information, see...

### ISSUE THREAD

**Issue by ghost** [SUSE/doc-styleguide#43] opened 2016-08-19 09:24 UTC
It might make sense to standardize the line we use to refer to other parts of the document.

Proposal:
- Some information already given, topic is clear: "For more information, see [xref]"
- Some information already given, topic is not completely clear/touches current topic tangentially:  "For more information about [topic], see [xref]".
- No information already given, topic is clear (rare?): "For information, see [xref]"
- No information already given, topic is  not completely clear/touches current topic tangentially: "For information about [topic], see [xref]".

Stats from doc-sle:

```
523 x for more information in XML (0 x for more information in entities)
28 x for information, see in XML (0 x for information, see in entities)
16 x for further information in XML (0 x for further information in entities)
7 x for additional information in XML (0 x for additional information in entities)
3 x for background information in XML (0 x for background information in entities)
1 x for additional background information in XML (0 x for additional background information in entities)
0 x for more background information in XML (0 x for more background information in entities)
0 x for further background information in XML (0 x for further background information in entities)
```

```
108 x for more information, see in XML (0 x for more information, see in entities)
27 x for more information, refer in XML (0 x for more information, refer in entities)

```

**Comment by dariavladykina** [comment] 2022-11-29 13:17
If this approach is accepted (do we want to endorse it?), I'd propose to add it to [Tone and Voice](https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-tone).

**Comment by jfaltenbacher** [comment] 2022-12-01 13:01
I am always in favor of standardization, also makes translation easier

**Comment by cwickert** [comment] 2022-12-01 13:52
This is a duplicate of 154 I think.

**Comment by dariavladykina** [comment] 2022-12-01 13:55
For more information is what we have voted for!

**Closed** 2023-02-10 11:59 UTC
Labels: type-enhancement, section-terminology
